export const calculatorAdmin = {
  texts: {
    titleEyebrow: "Elektro-Kosteneinschätzung",
    title: "Erste Kosteneinschätzung für Elektroarbeiten",
    intro:
      "Der Rechner liefert eine erste, nachvollziehbare Orientierung auf Basis fester Regeln. Für Mehrparteienhäuser wird bewusst nur eine grobe Spanne ausgegeben.",
    disclaimer: "Unverbindliche Ersteinschätzung ohne Besichtigung.",
    requestNote: "Nach der Einschätzung kannst du direkt eine Anfrage senden.",
  },

  objectTypes: [
    { value: "wohnung", label: "Wohnung", icon: "home" },
    { value: "einfamilienhaus", label: "Einfamilienhaus", icon: "home" },
    { value: "mehrparteienhaus", label: "Mehrparteienhaus", icon: "building" },
  ],

  packageTypes: [
    {
      value: "minimal",
      label: "Minimal",
      pricePerSqm: 95,
      description: "Für kostenbewusste Projekte mit funktionaler Grundausstattung.",
    },
    {
      value: "standard",
      label: "Standard",
      pricePerSqm: 115,
      description: "Für Familien mit solider, alltagstauglicher Ausstattung.",
      popular: true,
    },
    {
      value: "premium",
      label: "Premium",
      pricePerSqm: 130,
      description: "Für Projekte mit spürbar höherem Komfort und Reserven.",
    },
  ],

  mfhRanges: {
    minimal: 0.25,
    standard: 0.2,
    premium: 0.15,
  },

  technologyGroups: {
    grundtechnik: {
      title: "Grundtechnik",
      fields: ["hvNew", "uvCount", "underfloorHeating", "thermostats"],
    },
    ausstattung: {
      title: "Ausstattung",
      fields: ["networkPoints", "jalousieCount", "doorbell", "wallbox", "outdoorArea", "cellar"],
    },
  },

  fields: {
    hvNew: {
      key: "hvNew",
      label: "Hauptverteilung neu",
      type: "boolean",
      price: 4000,
      hint: "Komplett neuer Hauptverteiler.",
    },
    uvCount: {
      key: "uvCount",
      label: "Unterverteilungen neu",
      type: "integer",
      min: 0,
      max: 10,
      pricePerUnit: 1000,
      unitLabel: "Stück",
      hint: "Nur neue Unterverteilungen zusätzlich zur Hauptverteilung.",
    },
    underfloorHeating: {
      key: "underfloorHeating",
      label: "Fußbodenheizung vorhanden",
      type: "boolean",
      hint: "Schaltet Raumthermostate frei.",
    },
    thermostats: {
      key: "thermostats",
      label: "Raumthermostate",
      type: "integer",
      min: 0,
      max: 30,
      pricePerUnit: 180,
      unitLabel: "Räume",
      visibleWhen: (form) => Boolean(form.underfloorHeating),
      hint: "Nur relevant bei Fußbodenheizung.",
    },
    networkPoints: {
      key: "networkPoints",
      label: "Netzwerkanschlüsse",
      type: "integer",
      min: 0,
      max: 50,
      pricePerUnit: 120,
      unitLabel: "Anschlüsse",
      hint: "LAN / Netzwerk je Anschluss.",
    },
    jalousieCount: {
      key: "jalousieCount",
      label: "Elektrische Jalousien",
      type: "integer",
      min: 0,
      max: 50,
      pricePerUnit: 250,
      unitLabel: "Fenster",
    },
    doorbell: {
      key: "doorbell",
      label: "Klingelanlage neu",
      type: "boolean",
      price: 800,
      visibleWhen: (form) => form.objectType === "einfamilienhaus",
    },
    wallbox: {
      key: "wallbox",
      label: "Wallbox",
      type: "enum",
      options: [
        { value: "none", label: "Keine Wallbox", price: 0 },
        { value: "11kw", label: "Wallbox 11 kW", price: 2000 },
        { value: "22kw", label: "Wallbox 22 kW", price: 2400 },
      ],
      visibleWhen: (form) => form.objectType === "einfamilienhaus",
    },
    outdoorArea: {
      key: "outdoorArea",
      label: "Außenbereich",
      type: "boolean",
      price: 750,
      visibleWhen: (form) => form.objectType === "einfamilienhaus",
    },
    cellar: {
      key: "cellar",
      label: "Keller",
      type: "boolean",
      price: 1500,
      visibleWhen: (form) => form.objectType === "einfamilienhaus",
    },
    additionalSockets: {
      key: "additionalSockets",
      label: "Zusätzliche Steckdosen",
      type: "integer",
      min: 0,
      max: 100,
      pricePerUnit: 50,
      unitLabel: "Stück",
      hint: "Nur Steckdosen über den Paketstandard hinaus.",
    },
  },

  defaults: {
    objectType: "wohnung",
    sqm: "85",
    packageType: "standard",
    hvNew: false,
    uvCount: 0,
    underfloorHeating: false,
    thermostats: 0,
    networkPoints: 0,
    jalousieCount: 0,
    doorbell: false,
    wallbox: "none",
    outdoorArea: false,
    cellar: false,
    additionalSockets: 0,
    name: "",
    phone: "",
    email: "",
    zip: "",
    message: "",
  },
};
